/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Capture */

#ifndef _Included_Capture
#define _Included_Capture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Capture
 * Method:    initiateCapture
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Capture_initiateCapture
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Capture
 * Method:    stopCapture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Capture_stopCapture
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
