/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_red5_server_plugin_jni_callback_JNICallback */

#ifndef _Included_org_red5_server_plugin_jni_callback_JNICallback
#define _Included_org_red5_server_plugin_jni_callback_JNICallback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_red5_server_plugin_jni_callback_JNICallback
 * Method:    call
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_red5_server_plugin_jni_callback_JNICallback_call
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
