/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JacudaTest */

#ifndef _Included_JacudaTest
#define _Included_JacudaTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JacudaTest
 * Method:    getBuffer
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_JacudaTest_getBuffer
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     JacudaTest
 * Method:    getValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JacudaTest_getValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
